"""add job collect_github flag

Revision ID: 4e1a52675c62
Revises: 9e7726ce33e6
Create Date: 2026-09-21 22:03:24.408091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1a52675c62'
down_revision: Union[str, None] = '9e7726ce33e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('collect_github', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'collect_github')
    # ### end Alembic commands ###
